### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by chrisfilo** [datalad/open-brain-consent#10]
@cmaumet and @CPernet are working on the French translation of the ultimate consent form. It's available here: https://docs.google.com/document/d/10yacu6_ud9nrLjyiAWRuLgGMkYaCxXX6E1XfAsPCbVM/edit and we should merge it  this repository when it is done into.

**Comment by cmaumet** [comment]
Thanks for starting this @CPernet, @chrisfilo! I've done a first pass on the document and added comments. Ideally I would love if we could find a professional translator helping us refine this.

**Comment by CPernet** [comment]
hey google translator + my edits .. not that bad - maybe more community engagement would be enough


PS: @Camille Maumet<mailto:cmj.maumet@gmail.com>  just gave you edit rights


--
Dr Cyril Pernet,
Senior Academic Fellow, Neuroimaging Sciences
Software Sustainability Institute Fellow

The University of Edinburgh
Centre for Clinical Brain Sciences (CCBS)
Chancellor's Building, Room GU426D
49 Little France Crescent
Edinburgh EH16 4SB
cyril.pernet@ed.ac.uk<mailto:cyril.pernet@ed.ac.uk>
tel: +44(0)131 465 9530
<http://www.sbirc.ed.ac.uk/cyril>http://www.sbirc.ed.ac.uk/cyril
http://www.ed.ac.uk/edinburgh-imaging



________________________________

**Comment by emdupre** [comment]
Just checked the google doc, and it seems that there are no to-be-resolved comments at this point. Would this be safe to merge ?
