### ISSUE TITLE
Recommended citation ?

### ISSUE THREAD

**Issue by emdupre** [datalad/open-brain-consent#33]
Is there a recommended way to cite this resource ? I'd prefer link to a DOI rather than a URL, if at all possible !

Thanks !

**Comment by vsoch** [comment]
Maybe register with scicrunch to get an RRID? https://scicrunch.org/scicrunch

**Comment by yarikoptic** [comment]
With @chrisgorgo to get a paper about this effort published but never got to it. 
We have zenodo entry:
https://zenodo.org/record/3403176#.XXZzqaeYXjs so cite https://doi.org/10.5281/zenodo.1411525 ;-)

I will close this issue by committing a zenodo badge to README.md

If someone could take care about RRID -- would be great
